### ISSUE TITLE
Fix glitchy Replay icon on Mac

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#754] opened 2022-03-15 02:41 UTC
<img width="344" alt="image" src="https://user-images.githubusercontent.com/9154902/158295119-cdf9a393-c7f8-4617-bc57-6f942f5b99b2.png">

We've worked on this before but the issue still persists and makes our product look unprofessional.

**Comment by jasonLaster** [comment] 2022-04-24 21:55
@gideonred could you share your findings on `icns` not being supported?

Also tentatively assigned this one to you for next sprint. Feel free to change the iteration or assignee.

**Comment by gideonred** [comment] 2022-04-25 15:22
Closing this as a duplicate of https://github.com/RecordReplay/gecko-dev/issues/444, which has more info and is currently assigned to Ryan.

**Closed as completed by gideonred** 2022-04-25 15:22 UTC
