### ISSUE TITLE
Application icon is garbled

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#444] opened 2021-07-19 18:11 UTC
When Replay is installed, the logo should look like this,
<img width="753" alt="Screen Shot 2021-07-19 at 11 10 38 AM" src="https://user-images.githubusercontent.com/254562/126206940-fe634a46-4b96-440d-98ac-caf8fd67b23c.png">

but it is often looking garbled like this

![icon](https://user-images.githubusercontent.com/254562/126206710-0fc41957-63b0-40ab-87e6-ea958391b759.png)

**Comment by jasonLaster** [comment] 2021-09-27 14:17
removed from go/plan because it was just there pre-launch to be hyper focused on launch. in general go/plan is for larger projects

**Comment by ryanjduffy** [comment] 2021-10-08 00:16
Linking this in so I can close the tab and not lose track of it:

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/image-size-and-resolution/

**Comment by ryanjduffy** [comment] 2021-10-13 16:11
Closing this for now since it isn't reproducible and seems to be intermittent. We can reopen if it seems to become systemic.

**Comment by bvaughn** [comment] 2022-04-21 14:35
FWIW I'm seeing this consistently and so is someone I shared a Replay with on Twitter (who then installed gecko for the first time).

**Comment by gideonred** [comment] 2022-04-21 14:58
In case this helps, in the section "App Icon Attributes" of this link: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/ it goes into the technical details of what the icon should be using.

**Comment by gideonred** [comment] 2022-04-21 15:18
In the above tech doc they ask that we do not use icns files. Seems like we do:
![Screen Shot 2022-04-21 at 11 18 04 AM](https://user-images.githubusercontent.com/28845582/164490762-a4b81bb4-4970-4f82-8f1b-21679e206177.png)

**Comment by ryanjduffy** [comment] 2022-04-28 19:29
Oddly, when i create a new MacOS app in Xcode and drag icons into it, the output is an ICNS file ...

https://developer.apple.com/documentation/xcode/configuring-your-app-icon

**Comment by ryanjduffy** [comment] 2022-04-28 19:29
Going to try creating a fresh ICNS file with XCode with all the various sizes and see if that does the trick

**Closed as completed** 2022-04-28 22:57 UTC
Labels: bug, P1, mac
