### ISSUE TITLE
[UX] When recording WebGL, show error message explaining why the region has gone white

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#305] opened 2021-02-22 21:17 UTC
1. Load skittish page
2. Press record button in Replay browser
3. Page goes white

Here's a video of it:
https://share.descript.com/view/jCb13LOP0ZP

And here's a Replay:
https://replay.io/view?id=35319825-99f4-4ea3-939f-47b64375f7c5

**Comment by bhackett1024** [comment] 2021-02-22 21:50
It looks like the problem is that the page is using WebGL, which we don't support while recording.

**Comment by jonbell-lot23** [comment] 2021-02-22 22:07
Ah. Ok, renaming bug to reflect that we should should show an error message where possible.

**Comment by bhackett1024** [comment] 2021-09-07 14:03
dupe of https://github.com/RecordReplay/gecko-dev/issues/314

**Closed as completed by bhackett1024** 2021-09-07 14:03 UTC
