### ISSUE TITLE
Users are thrown off guard when the recording button refreshes the page

### ISSUE THREAD

**Issue by jaril** [replayio/gecko-dev#169] opened 2020-09-25 23:23 UTC
Refreshing the tab upon clicking the record button makes sense, but it throws users off guard. We should look into other options such as:
- adding an extra step, like displaying a small popup (like Loom), that requests their consent before refreshing their page
- opening the recording tab in a new tab instead of in the current tab

**Comment by jasonLaster** [comment] 2021-05-10 18:16
dupe of #339

**Closed as completed by jasonLaster** 2021-05-10 18:16 UTC
