### ISSUE TITLE
Stop recording doesn't open a new tab with the replay

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#415] opened 2021-06-11 19:14 UTC
Mark at Glide ran into a problem where starting to record and then stopping didn't actually open a new tab with the replay link.  Restarting the browser fixed this but we should get a better understanding of what might have happened and whether we can detect this problem and report it to telemetry when it happens to other users.

**Comment by ryanjduffy** [comment] 2021-06-21 18:06
@bhackett1024 - I started looking at this last week and talked with @jazzdan this morning a bit more. I had assumed that the existing gecko-dev telemetry was being handled by a replay server but that doesn't seem to be the case (at least based on Dan and my reading of the telemetry server code).

Do we want to add a rudimentary interface to the existing replay telemetry server to gecko-dev or add support for gecko telemetry to the replay telemetery server? Or some other option you've already considered?

**Comment by bhackett1024** [comment] 2021-06-21 18:31
> @bhackett1024 - I started looking at this last week and talked with @jazzdan this morning a bit more. I had assumed that the existing gecko-dev telemetry was being handled by a replay server but that doesn't seem to be the case (at least based on Dan and my reading of the telemetry server code).
> 
> Do we want to add a rudimentary interface to the existing replay telemetry server to gecko-dev or add support for gecko telemetry to the replay telemetery server? Or some other option you've already considered?

Yeah, we aren't picking up any of the regular browser telemetry at all.  I think it would be simplest to connect to the replay telemetry server for these sorts of pings, since it just uses a POST request.

**Comment by ryanjduffy** [comment] 2021-06-21 22:22
Some quick notes on my plan in that case:

* Add a pair of prefs, `replay.telemetry.server` and `replay.telemetry.enabled` to manage calling out to our endpoint
* Add a new module (probably next to `connection.js` in `devtools/server/actors/replay`) with a simple `pingTelemetry` method
* Add a handful of telemetry messages into `DevToolsStartup` to start collecting some data points
* Update the telemetry server to handle these new message and send them to honeycomb (I guess?)

cc: @loganfsmyth for insights on any of the above

**Comment by loganfsmyth** [comment] 2021-06-22 18:12
Sounds good to me, though I can't say I'm particularly familiar with FF telemetry.

**Comment by ryanjduffy** [comment] 2021-06-25 17:11
I've landed #428 to start tracking record button interactions to telemetry and RecordReplay/backend#2476 to handle those explicitly. I'm closing this as "done" under the assumption this will give us either enough data to identify the root cause or the telemetry gaps we need to fill.

**Closed as completed by ryanjduffy** 2021-06-25 17:11 UTC
